version: 2
before:
  hooks:
    - go mod download
    - go mod tidy
builds:
  -
    id: tcmux-darwin
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/k1LoW/tcmux/version.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
  -
    id: tcmux-linux
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/k1LoW/tcmux/version.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
archives:
  -
    id: tcmux-archive
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
      - goos: darwin
        formats:
          - zip
    files:
      - LICENSE
      - CREDITS
      - README.md
      - CHANGELOG.md
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
nfpms:
  -
    id: tcmux-nfpms
    file_name_template: "{{ .ProjectName }}_{{ .Version }}-1_{{ .Arch }}"
    ids:
      - tcmux-linux
    homepage: https://github.com/k1LoW/tcmux
    maintainer: Ken'ichiro Oyama <k1lowxb@gmail.com>
    description: "tcmux is a terminal and Claude Code mux viewer."
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    epoch: 1
release:
  use_existing_draft: true
